# Generated by Django 4.2 on 2023-04-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='data_pub',
            new_name='pub_date',
        ),
    ]
